/**
 * GDPR Art. 13/14 Privacy Policy — standalone document.
 *
 * Separate from Terms (LegalDisclaimer.tsx) by regulatory design:
 * GDPR requires the privacy notice to be its own surface so users
 * can find it without wading through ToS. We open it via a dedicated
 * footer link, with the same modal pattern as Terms.
 *
 * No ack checkbox here — Privacy Policy is informational, not
 * accept-or-decline. The user's right to be informed is satisfied
 * by us making the text available; they don't sign anything.
 *
 * If we ever change the practical processing (e.g. add analytics,
 * change retention period, add a sub-processor), the policy text
 * must be updated AND a notice posted to existing users at next
 * sign-in. For now the doc is intentionally short because we collect
 * very little.
 */

import { useState } from 'react';

interface Props {
  /** Render the trigger link only; the modal is mounted lazily on
   *  first open and stays in memory after to keep re-opens snappy. */
  triggerLabel?: string;
}

export function PrivacyPolicy({ triggerLabel = 'Privacy Policy' }: Props) {
  const [open, setOpen] = useState(false);
  return (
    <>
      <button
        type="button"
        onClick={() => setOpen(true)}
        className="text-cyan-400 underline-offset-2 hover:text-cyan-300 hover:underline"
      >
        {triggerLabel}
      </button>
      {open && <PrivacyModal onClose={() => setOpen(false)} />}
    </>
  );
}

function PrivacyModal({ onClose }: { onClose: () => void }) {
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/80 px-4 py-8 text-left"
      role="dialog"
      aria-modal="true"
      aria-labelledby="privacy-title"
    >
      <div className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-slate-700 bg-slate-900 shadow-xl">
        <div className="flex items-start justify-between border-b border-slate-800 px-6 py-4">
          <h2 id="privacy-title" className="text-lg font-semibold text-slate-100">
            Privacy Policy
          </h2>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="text-slate-400 hover:text-slate-200"
          >
            ✕
          </button>
        </div>

        <div className="space-y-4 px-6 py-5 text-sm text-slate-300">
          <p className="text-sm text-slate-400">
            Effective date: 2026-05-25. Last reviewed: 2026-05-25.
          </p>

          <Section title="1. Who we are (Data Controller)">
            OwlOrderFi is operated by an individual developer based in
            Romania (EU). For privacy-related inquiries, including
            requests to exercise your rights below, contact:{' '}
            <a
              href="mailto:privacy@owlorderfi.com"
              className="text-cyan-400 hover:text-cyan-300"
            >
              privacy@owlorderfi.com
            </a>
            . There is no Data Protection Officer requirement — we do
            not process special-category data and do not perform
            large-scale systematic monitoring (GDPR Art. 37).
          </Section>

          <Section title="2. What we collect">
            <ul className="ml-5 list-disc space-y-1">
              <li>
                <strong>Wallet address</strong> you connect with. Treated
                as personal data under GDPR (pseudonymous identifier).
                Used to identify your account, retrieve your orders, and
                verify ownership of orders you sign.
              </li>
              <li>
                <strong>Order metadata</strong> you submit — token pair,
                amounts, trigger price, schedule (for DCA/TWAP),
                slippage tolerance, your signature, the deadline. Stored
                so the keeper can execute when conditions are met.
              </li>
              <li>
                <strong>Execution records</strong> — slice fills,
                failure reasons, transaction hashes. Generated by the
                keeper, stored alongside your order.
              </li>
              <li>
                <strong>Authentication session</strong> — a hash of the
                JWT issued after you sign a sign-in message, plus the
                session expiry. No IP address or User-Agent is stored
                with the session. The JWT itself lives in your
                browser's localStorage; cleared on sign-out.
              </li>
              <li>
                <strong>Reverse-proxy access logs</strong> — standard
                HTTP request lines logged at the edge (IP address,
                timestamp, path, response status, User-Agent). Rotated
                automatically (oldest discarded after ~5 log files /
                250 MB). Used only for abuse mitigation and rate
                limiting.
              </li>
            </ul>
            <p className="mt-2">
              We do <strong>not</strong> collect: real name, email
              (unless you initiate contact with us), phone number,
              government IDs, date of birth, precise geolocation,
              behavioural analytics, or advertising identifiers.
            </p>
          </Section>

          <Section title="3. Legal basis (GDPR Art. 6)">
            <ul className="ml-5 list-disc space-y-1">
              <li>
                <strong>Contract performance</strong> (Art. 6(1)(b)):
                processing your wallet address, orders, signatures, and
                executions is necessary to provide the service you
                requested.
              </li>
              <li>
                <strong>Legitimate interest</strong> (Art. 6(1)(f)):
                server logs for abuse prevention and rate limiting.
                Retention is short.
              </li>
            </ul>
          </Section>

          <Section title="4. Retention">
            <ul className="ml-5 list-disc space-y-1">
              <li>
                <strong>Orders + executions</strong>: retained
                indefinitely for audit and historical accuracy. You can
                request deletion at any time (see rights below).
              </li>
              <li>
                <strong>Authentication sessions</strong>: expire after
                a fixed window (typically 30 days). Expired session
                rows are cleaned from the database periodically.
              </li>
              <li>
                <strong>Reverse-proxy access logs</strong>: rotated by
                file size (5 files × 50 MB), oldest discarded
                automatically. Effective retention depends on traffic
                volume — typically days to weeks.
              </li>
              <li>
                <strong>On-chain data</strong>: anything we submit to a
                public blockchain (execution transactions) is permanent
                and outside our control. The wallet address is publicly
                visible on the chain regardless of our retention.
              </li>
            </ul>
          </Section>

          <Section title="5. Recipients & sub-processors">
            <ul className="ml-5 list-disc space-y-1">
              <li>
                <strong>Hosting</strong>: self-hosted infrastructure
                (server in EU). No third-party cloud platform processes
                your data.
              </li>
              <li>
                <strong>RPC providers</strong>: when you submit an
                order, transaction data is sent to Ethereum-compatible
                RPC endpoints (Alchemy, public RPCs). They see the
                transaction payload but not your sign-in session.
              </li>
              <li>
                <strong>Wallet libraries</strong>: connecting your
                wallet loads RainbowKit / WalletConnect (Reown)
                resources from their infrastructure. See their own
                privacy policies.
              </li>
              <li>
                <strong>Block explorers</strong>: when we render an
                "tx ↗" link, clicking it opens an explorer page (Etherscan,
                Basescan, Arbiscan) which is operated by a third party
                and subject to their privacy policy.
              </li>
            </ul>
          </Section>

          <Section title="6. International transfers">
            All our infrastructure is hosted in the EU. Third-party
            services listed above (Alchemy, WalletConnect, block
            explorers) are operated globally and may process data in
            non-EU countries; data sent to them is the transaction
            payload only, which is by design public on the blockchain.
          </Section>

          <Section title="7. Your rights (GDPR Chapter III)">
            You have the right to:
            <ul className="ml-5 list-disc space-y-1">
              <li>
                <strong>Access</strong> (Art. 15) — request a copy of
                the data we hold about you.
              </li>
              <li>
                <strong>Rectification</strong> (Art. 16) — correct
                inaccurate data.
              </li>
              <li>
                <strong>Erasure</strong> (Art. 17) — request deletion of
                your account and orders. Note: on-chain transactions
                cannot be deleted; we can only remove our own DB
                records.
              </li>
              <li>
                <strong>Restriction</strong> (Art. 18) — limit how we
                use your data while a dispute is resolved.
              </li>
              <li>
                <strong>Portability</strong> (Art. 20) — receive your
                data in a structured, machine-readable format (we'll
                supply JSON).
              </li>
              <li>
                <strong>Object</strong> (Art. 21) — to processing based
                on legitimate interest.
              </li>
              <li>
                <strong>Complaint</strong> (Art. 77) — lodge a complaint
                with a competent data protection supervisory authority.
              </li>
            </ul>
            <p className="mt-2">
              To exercise any of these rights, email{' '}
              <a
                href="mailto:privacy@owlorderfi.com"
                className="text-cyan-400 hover:text-cyan-300"
              >
                privacy@owlorderfi.com
              </a>{' '}
              from the wallet sign-in address or include a signed
              message from that wallet so we can verify the request is
              coming from the account owner.
            </p>
          </Section>

          <Section title="8. Automated decision-making">
            We do not perform automated decision-making with legal or
            similarly significant effects. The keeper executes signed
            orders based on price triggers and schedules; it does not
            profile users or make discretionary decisions.
          </Section>

          <Section title="9. Children">
            The service is not directed at children under 16. We do not
            knowingly collect data from minors. If you believe a minor
            has used the service, contact us for deletion.
          </Section>

          <Section title="10. Changes to this policy">
            Material changes will be announced via a notice on the
            site at next sign-in. The "Last reviewed" date at the top
            of this page is updated whenever the text changes.
          </Section>
        </div>

        <div className="flex justify-end border-t border-slate-800 px-6 py-4">
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-medium text-slate-950 hover:bg-cyan-400"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h3 className="mb-1 text-sm font-semibold uppercase tracking-wider text-cyan-300/90">
        {title}
      </h3>
      <div className="text-sm text-slate-300">{children}</div>
    </div>
  );
}
